# Generated by Django 5.0.4 on 2024-05-04 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_category_remove_products_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image1',
            field=models.ImageField(default=None, upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
