# Generated by Django 5.0.4 on 2024-05-05 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_category_products_image1_products_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.sportscategory'),
            preserve_default=False,
        ),
    ]
